# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("file_path", models.TextField()),
                (
                    "allowed_tools",
                    models.TextField(blank=True, help_text="Comma-separated tool list"),
                ),
                ("content", models.TextField(help_text="Skill content/prompt")),
                ("frontmatter", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="plugins.plugin",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("plugin", "name")},
            },
        ),
    ]
