# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SettingsProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_name", models.CharField(max_length=100)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("project", "Project"),
                            ("local", "Local"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "parent_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent profile for inheritance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_profiles",
                        to="claude_settings.settingsprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "profile_name"],
                "unique_together": {("profile_name", "scope")},
            },
        ),
        migrations.CreateModel(
            name="ApiConfig",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="api_config",
                        serialize=False,
                        to="claude_settings.settingsprofile",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(blank=True, help_text="Encrypted API key"),
                ),
                ("api_base_url", models.URLField(blank=True)),
                ("organization_id", models.CharField(blank=True, max_length=100)),
                ("timeout_seconds", models.IntegerField(blank=True, null=True)),
                ("max_retries", models.IntegerField(blank=True, null=True)),
                ("retry_delay_ms", models.IntegerField(blank=True, null=True)),
                ("custom_headers_json", models.JSONField(blank=True, default=dict)),
                ("proxy_url", models.URLField(blank=True)),
                ("verify_ssl", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelPreference",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="model_preferences",
                        serialize=False,
                        to="claude_settings.settingsprofile",
                    ),
                ),
                ("default_model", models.CharField(blank=True, max_length=100)),
                (
                    "thinking_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("thinking_budget", models.IntegerField(blank=True, null=True)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("top_p", models.FloatField(blank=True, null=True)),
                ("top_k", models.IntegerField(blank=True, null=True)),
                ("custom_params_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThemeSetting",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="theme_settings",
                        serialize=False,
                        to="claude_settings.settingsprofile",
                    ),
                ),
                ("theme_name", models.CharField(max_length=100)),
                (
                    "color_scheme",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("primary_color", models.CharField(blank=True, max_length=20)),
                ("accent_color", models.CharField(blank=True, max_length=20)),
                ("background_color", models.CharField(blank=True, max_length=20)),
                ("text_color", models.CharField(blank=True, max_length=20)),
                ("custom_css", models.TextField(blank=True)),
                ("custom_colors_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SettingsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_key", models.CharField(db_index=True, max_length=200)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("changed_by", models.CharField(blank=True, max_length=100)),
                ("change_reason", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="claude_settings.settingsprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Settings histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "tool_pattern",
                    models.CharField(
                        help_text="Tool name pattern (supports wildcards)",
                        max_length=200,
                    ),
                ),
                (
                    "resource_pattern",
                    models.CharField(
                        blank=True, help_text="Resource path pattern", max_length=500
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("read", "Read"),
                            ("write", "Write"),
                            ("execute", "Execute"),
                            ("all", "All"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher = evaluated first"
                    ),
                ),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_rules",
                        to="claude_settings.settingsprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "-priority"],
                        name="claude_sett_rule_ty_e9805f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SettingsValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setting_key", models.CharField(db_index=True, max_length=200)),
                ("setting_value", models.TextField(blank=True)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("object", "Object"),
                            ("array", "Array"),
                            ("null", "Null"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(default=False, help_text="Hide value in UI"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="claude_settings.settingsprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "setting_key"],
                "unique_together": {("profile", "setting_key")},
            },
        ),
    ]
