# Generated by Django 5.2.7 on 2026-01-28 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claude_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalPermissionSettings",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="global_permissions",
                        serialize=False,
                        to="claude_settings.settingsprofile",
                    ),
                ),
                (
                    "additional_directories",
                    models.JSONField(
                        default=list,
                        help_text="Additional directories Claude can access",
                    ),
                ),
                (
                    "default_mode",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("acceptEdits", "Accept Edits"),
                            ("dontAsk", "Don't Ask"),
                            ("bypassPermissions", "Bypass Permissions"),
                        ],
                        default="normal",
                        help_text="Default permission mode",
                        max_length=30,
                    ),
                ),
                (
                    "disable_bypass_mode",
                    models.BooleanField(
                        default=False, help_text="Restrict bypass mode availability"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Permission Settings",
                "verbose_name_plural": "Global Permission Settings",
            },
        ),
        migrations.CreateModel(
            name="SandboxConfig",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sandbox_config",
                        serialize=False,
                        to="claude_settings.settingsprofile",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "auto_allow_bash_if_sandboxed",
                    models.BooleanField(
                        default=True,
                        help_text="Auto-allow Bash commands when sandboxing is enabled",
                    ),
                ),
                (
                    "excluded_commands",
                    models.JSONField(
                        default=list, help_text="Commands excluded from sandboxing"
                    ),
                ),
                ("allow_unsandboxed_commands", models.BooleanField(default=False)),
                ("enable_weaker_nested_sandbox", models.BooleanField(default=False)),
                (
                    "allow_unix_sockets",
                    models.JSONField(
                        default=list, help_text="Unix socket paths allowed"
                    ),
                ),
                ("allow_local_binding", models.BooleanField(default=True)),
                ("http_proxy_port", models.IntegerField(blank=True, null=True)),
                ("socks_proxy_port", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sandbox Configuration",
            },
        ),
        migrations.RemoveField(
            model_name="permissionrule",
            name="scope",
        ),
        migrations.AddField(
            model_name="permissionrule",
            name="access_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("read", "Read"),
                    ("write", "Write"),
                    ("execute", "Execute"),
                    ("all", "All"),
                ],
                help_text="Access level for this rule",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="permissionrule",
            name="rule_type",
            field=models.CharField(
                choices=[("allow", "Allow"), ("ask", "Ask"), ("deny", "Deny")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="settingsprofile",
            name="scope",
            field=models.CharField(
                choices=[
                    ("user", "User (~/.claude/)"),
                    ("project", "Project (.claude/)"),
                    ("local", "Local (.claude/*.local.*)"),
                    ("managed", "Managed (Enterprise)"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EnvironmentVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variable_name", models.CharField(max_length=100)),
                ("variable_value", models.TextField()),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False, help_text="If True, value is masked in UI"
                    ),
                ),
                (
                    "is_script",
                    models.BooleanField(
                        default=False,
                        help_text="If True, value is result of script execution",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment_variables",
                        to="claude_settings.settingsprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "variable_name"],
                "unique_together": {("profile", "variable_name")},
            },
        ),
    ]
