# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claude_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutputPreference",
            fields=[
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="output_preferences",
                        serialize=False,
                        to="claude_settings.settingsprofile",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "Text"),
                            ("markdown", "Markdown"),
                            ("json", "JSON"),
                            ("auto", "Auto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "verbosity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiet", "Quiet"),
                            ("normal", "Normal"),
                            ("verbose", "Verbose"),
                            ("debug", "Debug"),
                        ],
                        max_length=20,
                    ),
                ),
                ("show_thinking", models.BooleanField(blank=True, null=True)),
                ("show_line_numbers", models.BooleanField(blank=True, null=True)),
                ("syntax_highlighting", models.BooleanField(blank=True, null=True)),
                ("max_output_lines", models.IntegerField(blank=True, null=True)),
                (
                    "truncation_strategy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("head", "Head"),
                            ("tail", "Tail"),
                            ("middle", "Middle"),
                            ("smart", "Smart"),
                        ],
                        max_length=20,
                    ),
                ),
                ("custom_styles_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
