# Generated by Django 5.2.7 on 2026-01-28 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claude_sessions", "0001_initial"),
        ("output_styles", "0001_initial"),
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutputStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style_name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier (e.g., 'concise', 'verbose', 'explanatory')",
                        max_length=100,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this style does"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Complete system prompt content that REPLACES the default"
                    ),
                ),
                (
                    "keep_coding_instructions",
                    models.BooleanField(
                        default=False,
                        help_text="If True, coding instructions are preserved alongside this style",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("builtin", "Built-in"),
                            ("user", "User Custom"),
                            ("project", "Project"),
                            ("plugin", "Plugin"),
                            ("managed", "Managed"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("communication", "Communication Style"),
                            ("expertise", "Expertise Level"),
                            ("format", "Response Format"),
                            ("context", "Context-specific"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_styles",
                        to="plugins.plugin",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "style_name"],
                "unique_together": {("source", "style_name")},
            },
        ),
        migrations.CreateModel(
            name="OutputStyleActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activation_source",
                    models.CharField(
                        choices=[
                            ("settings", "Settings Default"),
                            ("command", "Slash Command"),
                            ("hook", "Hook"),
                            ("api", "API Override"),
                        ],
                        default="settings",
                        max_length=30,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_activations",
                        to="claude_sessions.session",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="output_styles.outputstyle",
                    ),
                ),
            ],
            options={
                "ordering": ["-activated_at"],
            },
        ),
        migrations.DeleteModel(
            name="OutputPreference",
        ),
    ]
