# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claude_sessions", "0001_initial"),
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=30)),
                (
                    "triggered_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(db_index=True)),
                ("input_json", models.JSONField(blank=True, null=True)),
                ("output_json", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("timeout_occurred", models.BooleanField(default=False)),
                (
                    "plugin_id",
                    models.CharField(
                        blank=True, help_text="Plugin identifier string", max_length=100
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="HookDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PreToolUse", "Pre Tool Use"),
                            ("PostToolUse", "Post Tool Use"),
                            ("Stop", "Stop"),
                            ("SubagentStop", "Subagent Stop"),
                            ("SessionStart", "Session Start"),
                            ("SessionEnd", "Session End"),
                            ("UserPromptSubmit", "User Prompt Submit"),
                            ("PreCompact", "Pre Compact"),
                            ("Notification", "Notification"),
                            ("ToolError", "Tool Error"),
                            ("ToolSuccess", "Tool Success"),
                            ("ModelResponse", "Model Response"),
                            ("Shutdown", "Shutdown"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("script_path", models.TextField()),
                ("timeout_ms", models.IntegerField(default=5000)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Lower = higher priority"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "plugin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Plugin that provides this hook (null for system hooks)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hook_definitions",
                        to="plugins.plugin",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "event_type"],
            },
        ),
        migrations.CreateModel(
            name="HookEventModelResponse",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="modelresponse_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                ("finish_reason", models.CharField(blank=True, max_length=50)),
                (
                    "latency_ms",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("cache_hit", models.BooleanField(default=False)),
                ("tool_calls_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventNotification",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("notification_title", models.CharField(blank=True, max_length=200)),
                ("notification_message", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("action_required", models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventPostToolUse",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="posttooluse_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("tool_input", models.TextField(blank=True)),
                ("tool_output", models.TextField(blank=True)),
                ("tool_success", models.BooleanField(blank=True, null=True)),
                ("injected_context", models.TextField(blank=True)),
                ("injected_at_position", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventPreCompact",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="precompact_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                (
                    "current_tokens",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("max_tokens", models.IntegerField(blank=True, null=True)),
                ("compaction_strategy", models.CharField(blank=True, max_length=50)),
                ("messages_before", models.IntegerField(blank=True, null=True)),
                ("messages_to_remove", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventPreToolUse",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pretooluse_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("tool_input", models.TextField(blank=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("block", "Block"),
                            ("modify", "Modify"),
                        ],
                        db_index=True,
                        default="allow",
                        max_length=10,
                    ),
                ),
                ("modified_input", models.TextField(blank=True)),
                ("block_reason", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventSessionEnd",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sessionend_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("total_turns", models.IntegerField(blank=True, null=True)),
                ("total_input_tokens", models.IntegerField(blank=True, null=True)),
                ("total_output_tokens", models.IntegerField(blank=True, null=True)),
                ("tools_used_count", models.IntegerField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HookEventSessionStart",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sessionstart_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("working_directory", models.TextField(blank=True)),
                (
                    "user_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("client_version", models.CharField(blank=True, max_length=50)),
                (
                    "model_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("session_config", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventShutdown",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="shutdown_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                (
                    "shutdown_reason",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("uptime_seconds", models.IntegerField(blank=True, null=True)),
                ("active_sessions", models.IntegerField(blank=True, null=True)),
                ("pending_tasks", models.IntegerField(blank=True, null=True)),
                ("cleanup_status", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventStop",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stop_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                (
                    "stop_reason",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("message_count", models.IntegerField(blank=True, null=True)),
                ("finish_reason", models.CharField(blank=True, max_length=50)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventSubagentStop",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="subagentstop_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                (
                    "subagent_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("subagent_type", models.CharField(blank=True, max_length=50)),
                ("parent_session_id", models.CharField(blank=True, max_length=64)),
                (
                    "exit_status",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("result_summary", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventToolError",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="toolerror_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("tool_input", models.TextField(blank=True)),
                (
                    "error_type",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("error_message", models.TextField(blank=True)),
                ("stack_trace", models.TextField(blank=True)),
                ("retry_attempted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventToolSuccess",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="toolsuccess_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("tool_input", models.TextField(blank=True)),
                ("tool_output", models.TextField(blank=True)),
                (
                    "execution_time_ms",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("output_size_bytes", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HookEventUserPromptSubmit",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="userpromptsubmit_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("prompt_text", models.TextField(blank=True)),
                (
                    "prompt_length",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("attachments_count", models.IntegerField(default=0)),
                ("is_continuation", models.BooleanField(default=False)),
                ("context_size_tokens", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="hookevent",
            name="hook_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="hooks.hookdefinition",
            ),
        ),
        migrations.AddField(
            model_name="hookevent",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hook_events",
                to="claude_sessions.session",
            ),
        ),
        migrations.AddIndex(
            model_name="hookdefinition",
            index=models.Index(
                fields=["event_type", "enabled"], name="hooks_hookd_event_t_fa39a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hookdefinition",
            index=models.Index(
                fields=["priority"], name="hooks_hookd_priorit_6d8c29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hookevent",
            index=models.Index(
                fields=["event_type", "-triggered_at"],
                name="hooks_hooke_event_t_2576a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hookevent",
            index=models.Index(
                fields=["success", "-triggered_at"],
                name="hooks_hooke_success_21010c_idx",
            ),
        ),
    ]
