# Generated by Django 5.2.7 on 2026-01-28 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hooks", "0001_initial"),
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HookEventPermissionRequest",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="permissionrequest_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("tool_input", models.TextField(blank=True)),
                ("tool_use_id", models.CharField(blank=True, max_length=64)),
                ("permission_mode", models.CharField(blank=True, max_length=30)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("deny", "Deny"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decision_source", models.CharField(blank=True, max_length=30)),
                ("updated_input", models.TextField(blank=True)),
                ("denial_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Hook Event: Permission Request",
                "verbose_name_plural": "Hook Events: Permission Requests",
            },
        ),
        migrations.CreateModel(
            name="HookEventPostToolUseFailure",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="posttoolusefailure_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("tool_input", models.TextField(blank=True)),
                ("tool_use_id", models.CharField(blank=True, max_length=64)),
                (
                    "error_type",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("error_message", models.TextField(blank=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("stderr", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Hook Event: Post Tool Use Failure",
                "verbose_name_plural": "Hook Events: Post Tool Use Failures",
            },
        ),
        migrations.CreateModel(
            name="HookEventSetup",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="setup_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("init", "Init"),
                            ("init_only", "Init Only"),
                            ("maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("working_directory", models.TextField(blank=True)),
                ("additional_context", models.TextField(blank=True)),
                ("env_vars_set", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Hook Event: Setup",
                "verbose_name_plural": "Hook Events: Setup",
            },
        ),
        migrations.CreateModel(
            name="HookEventSubagentStart",
            fields=[
                (
                    "hook_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="subagentstart_detail",
                        serialize=False,
                        to="hooks.hookevent",
                    ),
                ),
                ("agent_id", models.CharField(db_index=True, max_length=64)),
                ("agent_type", models.CharField(db_index=True, max_length=50)),
                ("parent_session_id", models.CharField(blank=True, max_length=64)),
                ("task_description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Hook Event: Subagent Start",
                "verbose_name_plural": "Hook Events: Subagent Starts",
            },
        ),
        migrations.AddField(
            model_name="hookdefinition",
            name="hook_type",
            field=models.CharField(
                choices=[("command", "Command"), ("prompt", "Prompt")],
                default="command",
                help_text="'command' runs a script, 'prompt' injects text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hookdefinition",
            name="matcher",
            field=models.CharField(
                blank=True,
                help_text="Tool pattern matcher (regex) for tool-specific hooks",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="hookdefinition",
            name="prompt_text",
            field=models.TextField(
                blank=True, help_text="Prompt content for prompt-type hooks"
            ),
        ),
        migrations.AddField(
            model_name="hookdefinition",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "User (~/.claude/)"),
                    ("project", "Project (.claude/)"),
                    ("local", "Local (.claude/*.local.*)"),
                    ("plugin", "Plugin"),
                    ("skill", "Skill"),
                    ("agent", "Agent"),
                    ("policy", "Policy (Managed)"),
                ],
                help_text="Origin of this hook definition",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hookdefinition",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PreToolUse", "Pre Tool Use"),
                    ("PostToolUse", "Post Tool Use"),
                    ("PostToolUseFailure", "Post Tool Use Failure"),
                    ("PermissionRequest", "Permission Request"),
                    ("Stop", "Stop"),
                    ("SubagentStart", "Subagent Start"),
                    ("SubagentStop", "Subagent Stop"),
                    ("Setup", "Setup"),
                    ("SessionStart", "Session Start"),
                    ("SessionEnd", "Session End"),
                    ("UserPromptSubmit", "User Prompt Submit"),
                    ("PreCompact", "Pre Compact"),
                    ("Notification", "Notification"),
                    ("ToolError", "Tool Error"),
                    ("ToolSuccess", "Tool Success"),
                    ("ModelResponse", "Model Response"),
                    ("Shutdown", "Shutdown"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hookdefinition",
            name="script_path",
            field=models.TextField(
                blank=True, help_text="Path to hook script (for command type)"
            ),
        ),
        migrations.AddIndex(
            model_name="hookdefinition",
            index=models.Index(
                fields=["hook_type"], name="hooks_hookd_hook_ty_dfd7f1_idx"
            ),
        ),
    ]
