# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyIndex",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("session_count", models.IntegerField(default=0)),
                ("event_count", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name_plural": "Daily indices",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Message UUID",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parent_uuid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Parent message for threading",
                        max_length=64,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("progress", "Progress"),
                            ("system", "System"),
                            ("summary", "Summary"),
                            ("file-history-snapshot", "File History Snapshot"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "is_sidechain",
                    models.BooleanField(
                        default=False, help_text="Is this a subagent message?"
                    ),
                ),
                ("cwd", models.TextField(blank=True)),
                ("git_branch", models.CharField(blank=True, max_length=255)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, db_index=True, max_length=100)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("stop_reason", models.CharField(blank=True, max_length=50)),
                ("stop_sequence", models.CharField(blank=True, max_length=50)),
                (
                    "tool_use_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("parent_tool_use_id", models.CharField(blank=True, max_length=64)),
                (
                    "content_text",
                    models.TextField(blank=True, help_text="Plain text content"),
                ),
                (
                    "content_json",
                    models.JSONField(
                        blank=True, help_text="Structured content", null=True
                    ),
                ),
                (
                    "data_json",
                    models.JSONField(
                        blank=True, help_text="Additional data", null=True
                    ),
                ),
                ("snapshot_json", models.JSONField(blank=True, null=True)),
                ("is_snapshot_update", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SyncState",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "last_position",
                    models.BigIntegerField(
                        default=0, help_text="Byte position in JSONL file"
                    ),
                ),
                ("last_sync", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgressEvent",
            fields=[
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="progress_event",
                        serialize=False,
                        to="claude_sessions.message",
                    ),
                ),
                (
                    "hook_event",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "hook_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("command", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="UUID session identifier",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="Session start timestamp"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="Session end timestamp", null=True
                    ),
                ),
                ("cwd", models.TextField(blank=True, help_text="Working directory")),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Session summary (auto-generated)"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Session tags"
                    ),
                ),
                ("event_count", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="claude_sess_started_e20ae6_idx"
                    ),
                    models.Index(fields=["cwd"], name="claude_sess_cwd_015d58_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="claude_sessions.session",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(db_index=True, max_length=50)),
                ("ts", models.DateTimeField(help_text="Event timestamp")),
                ("agent_session_num", models.IntegerField(default=0)),
                ("data", models.JSONField(default=dict)),
                ("content", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="claude_sessions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["ts"],
            },
        ),
        migrations.CreateModel(
            name="ToolUse",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Tool use ID",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("input_json", models.JSONField(help_text="Tool input parameters")),
                ("description", models.TextField(blank=True)),
                ("result_content", models.TextField(blank=True)),
                ("is_error", models.BooleanField(blank=True, db_index=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_uses",
                        to="claude_sessions.message",
                    ),
                ),
                (
                    "result_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_results_for",
                        to="claude_sessions.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="token_usage",
                        serialize=False,
                        to="claude_sessions.message",
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cache_creation_input_tokens", models.IntegerField(default=0)),
                ("cache_read_input_tokens", models.IntegerField(default=0)),
                ("cache_creation_ephemeral_5m", models.IntegerField(default=0)),
                ("cache_creation_ephemeral_1h", models.IntegerField(default=0)),
                ("service_tier", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["input_tokens", "output_tokens"],
                        name="claude_sess_input_t_0e5f21_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_index", models.IntegerField(help_text="Order within message")),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("tool_use", "Tool Use"),
                            ("tool_result", "Tool Result"),
                            ("thinking", "Thinking"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("text_content", models.TextField(blank=True)),
                (
                    "tool_use_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("tool_name", models.CharField(blank=True, max_length=100)),
                ("tool_input_json", models.JSONField(blank=True, null=True)),
                ("tool_description", models.TextField(blank=True)),
                ("tool_result_content", models.TextField(blank=True)),
                ("tool_result_is_error", models.BooleanField(blank=True, null=True)),
                (
                    "tool_result_for_tool_use_id",
                    models.CharField(blank=True, max_length=64),
                ),
                ("thinking_content", models.TextField(blank=True)),
                ("thinking_signature", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="claude_sessions.message",
                    ),
                ),
            ],
            options={
                "ordering": ["message", "block_index"],
                "indexes": [
                    models.Index(
                        fields=["block_type"], name="claude_sess_block_t_0880d9_idx"
                    ),
                    models.Index(
                        fields=["tool_name"], name="claude_sess_tool_na_52eead_idx"
                    ),
                ],
                "unique_together": {("message", "block_index")},
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "timestamp"], name="claude_sess_session_53a251_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["type", "-timestamp"], name="claude_sess_type_e4006d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["model", "-timestamp"], name="claude_sess_model_cffd84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["session", "ts"], name="claude_sess_session_40a6b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["type"], name="claude_sess_type_178b53_idx"),
        ),
        migrations.AddIndex(
            model_name="tooluse",
            index=models.Index(
                fields=["tool_name", "-created_at"],
                name="claude_sess_tool_na_1c3a4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tooluse",
            index=models.Index(
                fields=["is_error", "-created_at"],
                name="claude_sess_is_erro_3d9054_idx",
            ),
        ),
    ]
