# Generated by Django 5.2.7 on 2026-01-28 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claude_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Queue operation UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("enqueue", "Enqueue"), ("remove", "Remove")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "content",
                    models.TextField(blank=True, help_text="Queue item content"),
                ),
                (
                    "queue_item_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the queue item being operated on",
                        max_length=64,
                    ),
                ),
                (
                    "subagent_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Subagent associated with this queue operation",
                        max_length=64,
                    ),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True,
                        help_text="Additional queue operation metadata",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ThinkingMetadata",
            fields=[
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="thinking_metadata",
                        serialize=False,
                        to="claude_sessions.message",
                    ),
                ),
                (
                    "max_thinking_tokens",
                    models.IntegerField(help_text="Maximum thinking tokens allowed"),
                ),
                (
                    "budget_tokens",
                    models.IntegerField(
                        blank=True, help_text="Budget tokens allocated", null=True
                    ),
                ),
                (
                    "thinking_level",
                    models.CharField(
                        blank=True,
                        help_text="Thinking level: low, medium, high, custom",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="api_message_id",
            field=models.CharField(
                blank=True, help_text="API-level message ID from Claude", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_compact_summary",
            field=models.BooleanField(
                default=False, help_text="Message is a compact summary"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="is_meta",
            field=models.BooleanField(default=False, help_text="Meta message flag"),
        ),
        migrations.AddField(
            model_name="message",
            name="is_visible_in_transcript_only",
            field=models.BooleanField(
                default=False,
                help_text="Message visible only in transcript, not conversation",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="logical_parent_uuid",
            field=models.CharField(
                blank=True,
                help_text="Parent UUID for compact boundaries",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="permission_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default"),
                    ("acceptEdits", "Accept Edits"),
                    ("dontAsk", "Don't Ask"),
                    ("bypassPermissions", "Bypass Permissions"),
                ],
                help_text="Permission mode during this message",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="slug",
            field=models.CharField(
                blank=True, help_text="Session slug reference", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="system_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("compact_boundary", "Compact Boundary"),
                    ("stop_hook_summary", "Stop Hook Summary"),
                    ("turn_duration", "Turn Duration"),
                    ("error", "Error"),
                    ("warning", "Warning"),
                    ("info", "Info"),
                ],
                db_index=True,
                help_text="Subtype for system messages: compact_boundary, stop_hook_summary, turn_duration",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user_type",
            field=models.CharField(
                blank=True, help_text="User type: 'external', 'internal'", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="agent_id",
            field=models.CharField(
                blank=True, help_text="Agent ID for agent_progress", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="elapsed_time_seconds",
            field=models.FloatField(
                blank=True, help_text="Duration for bash_progress", null=True
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="full_output",
            field=models.TextField(
                blank=True, help_text="Complete output for bash_progress"
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="normalized_messages",
            field=models.JSONField(
                blank=True,
                help_text="Normalized messages for agent_progress",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="output",
            field=models.TextField(
                blank=True, help_text="Current output for bash_progress"
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="progress_type",
            field=models.CharField(
                choices=[
                    ("hook_progress", "Hook Progress"),
                    ("bash_progress", "Bash Progress"),
                    ("agent_progress", "Agent Progress"),
                    ("query_update", "Query Update"),
                    ("search_results_received", "Search Results"),
                    ("tool_progress", "Tool Progress"),
                ],
                db_index=True,
                default="hook_progress",
                help_text="Type of progress event",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="prompt",
            field=models.TextField(
                blank=True, help_text="Agent prompt for agent_progress"
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="query",
            field=models.TextField(
                blank=True,
                help_text="Query text for query_update and search_results_received",
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="result_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of results for search_results_received",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="progressevent",
            name="total_lines",
            field=models.IntegerField(
                blank=True, help_text="Line count for bash_progress", null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="git_branch",
            field=models.CharField(
                blank=True,
                help_text="Primary git branch at session start",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Human-readable session name (e.g., 'calm-dreaming-backus')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="user_type",
            field=models.CharField(
                blank=True, help_text="User type: 'external', 'internal'", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="version",
            field=models.CharField(
                blank=True, help_text="Claude Code version", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("progress", "Progress"),
                    ("system", "System"),
                    ("summary", "Summary"),
                    ("file-history-snapshot", "File History Snapshot"),
                    ("queue-operation", "Queue Operation"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["system_subtype"], name="claude_sess_system__95b7ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progressevent",
            index=models.Index(
                fields=["progress_type"], name="claude_sess_progres_954d11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progressevent",
            index=models.Index(
                fields=["hook_event"], name="claude_sess_hook_ev_b59ec5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="progressevent",
            index=models.Index(
                fields=["agent_id"], name="claude_sess_agent_i_8e3c37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["slug"], name="claude_sess_slug_ae83c7_idx"),
        ),
        migrations.AddField(
            model_name="queueoperation",
            name="message",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated message if any",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_operations",
                to="claude_sessions.message",
            ),
        ),
        migrations.AddField(
            model_name="queueoperation",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_operations",
                to="claude_sessions.session",
            ),
        ),
        migrations.AddIndex(
            model_name="queueoperation",
            index=models.Index(
                fields=["session", "timestamp"], name="claude_sess_session_214a77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queueoperation",
            index=models.Index(
                fields=["operation", "-timestamp"],
                name="claude_sess_operati_1da79e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="queueoperation",
            index=models.Index(
                fields=["subagent_id"], name="claude_sess_subagen_15bd1a_idx"
            ),
        ),
    ]
