# Generated by Django 5.2.7 on 2026-01-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claude_sessions", "0002_sessions_enhancement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Session slug reference",
                max_length=100,
            ),
        ),
    ]
