# Generated by Django 5.2.7 on 2026-01-29 00:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claude_sessions", "0003_add_message_slug_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "project_path",
                    models.TextField(blank=True, help_text="Empty = all projects"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="Empty = all models", max_length=100
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True, help_text="Empty = all user types", max_length=20
                    ),
                ),
                ("total_input_tokens", models.BigIntegerField(default=0)),
                ("total_output_tokens", models.BigIntegerField(default=0)),
                ("total_cache_write_tokens", models.BigIntegerField(default=0)),
                ("total_cache_read_tokens", models.BigIntegerField(default=0)),
                ("total_thinking_tokens", models.BigIntegerField(default=0)),
                (
                    "total_input_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_output_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_cache_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_thinking_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("session_count", models.IntegerField(default=0)),
                ("message_count", models.IntegerField(default=0)),
                (
                    "unique_project_count",
                    models.IntegerField(
                        default=0, help_text="Only for all-projects rollup"
                    ),
                ),
                ("aggregated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["-date", "project_path"],
                        name="billing_dai_date_3686e1_idx",
                    ),
                    models.Index(
                        fields=["-date", "model"], name="billing_dai_date_ada728_idx"
                    ),
                    models.Index(
                        fields=["-date", "user_type"],
                        name="billing_dai_date_c995ed_idx",
                    ),
                    models.Index(
                        fields=["-total_cost"], name="billing_dai_total_c_d67a8d_idx"
                    ),
                ],
                "unique_together": {("date", "project_path", "model", "user_type")},
            },
        ),
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        help_text="Model identifier (e.g., 'claude-opus-4-5-20251101')",
                        max_length=100,
                    ),
                ),
                (
                    "model_family",
                    models.CharField(
                        db_index=True,
                        help_text="Model family: opus, sonnet, haiku",
                        max_length=50,
                    ),
                ),
                (
                    "model_generation",
                    models.CharField(
                        blank=True,
                        help_text="Model generation: 4.5, 4.1, 4, 3.5, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "input_price_mtok",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Input token price per million tokens",
                        max_digits=10,
                    ),
                ),
                (
                    "output_price_mtok",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Output token price per million tokens",
                        max_digits=10,
                    ),
                ),
                (
                    "cache_write_price_mtok",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cache creation price per million tokens",
                        max_digits=10,
                    ),
                ),
                (
                    "cache_read_price_mtok",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Cache read price per million tokens",
                        max_digits=10,
                    ),
                ),
                (
                    "cache_ephemeral_5m_price_mtok",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="5-minute ephemeral cache price per MTok",
                        max_digits=10,
                    ),
                ),
                (
                    "cache_ephemeral_1h_price_mtok",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="1-hour ephemeral cache price per MTok",
                        max_digits=10,
                    ),
                ),
                (
                    "thinking_price_mtok",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Extended thinking token price per MTok",
                        max_digits=10,
                    ),
                ),
                (
                    "batch_input_price_mtok",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Batch API input price per MTok",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "batch_output_price_mtok",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Batch API output price per MTok",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        db_index=True, help_text="Date this pricing becomes effective"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Date this pricing ends (null = still current)",
                        null=True,
                    ),
                ),
                (
                    "is_deprecated",
                    models.BooleanField(default=False, help_text="Model is deprecated"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-effective_from", "model_family"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "-effective_from"],
                        name="billing_pri_model_n_1163f5_idx",
                    ),
                    models.Index(
                        fields=["model_family", "-effective_from"],
                        name="billing_pri_model_f_eebc77_idx",
                    ),
                ],
                "unique_together": {("model_name", "effective_from")},
            },
        ),
        migrations.CreateModel(
            name="RateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("user", "User"),
                            ("project", "Project"),
                            ("model", "Model"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "scope_value",
                    models.CharField(
                        blank=True,
                        help_text="Specific value for scope (e.g., project path, model name)",
                        max_length=200,
                    ),
                ),
                (
                    "limit_type",
                    models.CharField(
                        choices=[
                            ("tokens", "Tokens"),
                            ("input_tokens", "Input Tokens"),
                            ("output_tokens", "Output Tokens"),
                            ("requests", "Requests"),
                            ("cost", "Cost (USD)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("minute", "Per Minute"),
                            ("hour", "Per Hour"),
                            ("day", "Per Day"),
                            ("month", "Per Month"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "limit_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum value for the period",
                        max_digits=14,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_hard_limit",
                    models.BooleanField(
                        default=False, help_text="If True, block requests when exceeded"
                    ),
                ),
                (
                    "alert_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.80"),
                        help_text="Percentage at which to trigger alert (0.80 = 80%)",
                        max_digits=5,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scope", "name"],
                "indexes": [
                    models.Index(
                        fields=["scope", "scope_value", "is_active"],
                        name="billing_rat_scope_303692_idx",
                    ),
                    models.Index(
                        fields=["limit_type", "period"],
                        name="billing_rat_limit_t_1c9f1d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionCost",
            fields=[
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cost",
                        serialize=False,
                        to="claude_sessions.session",
                    ),
                ),
                ("total_input_tokens", models.BigIntegerField(default=0)),
                ("total_output_tokens", models.BigIntegerField(default=0)),
                ("total_cache_write_tokens", models.BigIntegerField(default=0)),
                ("total_cache_read_tokens", models.BigIntegerField(default=0)),
                ("total_thinking_tokens", models.BigIntegerField(default=0)),
                (
                    "total_input_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_output_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_cache_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_thinking_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_adjustment",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Sum of all adjustments",
                        max_digits=14,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "adjusted_total",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Total cost after adjustments",
                        max_digits=14,
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                (
                    "billable_message_count",
                    models.IntegerField(
                        default=0, help_text="Messages with non-zero cost"
                    ),
                ),
                (
                    "primary_model",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Most-used model in session",
                        max_length=100,
                    ),
                ),
                (
                    "project_path",
                    models.TextField(blank=True, help_text="Session working directory"),
                ),
                (
                    "session_started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False, help_text="Session has ended and costs are final"
                    ),
                ),
                ("aggregated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_cost_count",
                    models.IntegerField(
                        default=0, help_text="Number of MessageCost records aggregated"
                    ),
                ),
            ],
            options={
                "ordering": ["-total_cost"],
                "indexes": [
                    models.Index(
                        fields=["-total_cost"], name="billing_ses_total_c_a4c13d_idx"
                    ),
                    models.Index(
                        fields=["primary_model", "-total_cost"],
                        name="billing_ses_primary_dd5250_idx",
                    ),
                    models.Index(
                        fields=["is_complete", "-aggregated_at"],
                        name="billing_ses_is_comp_c85b21_idx",
                    ),
                    models.Index(
                        fields=["-session_started_at"],
                        name="billing_ses_session_cb8190_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CostAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("refund", "Refund"),
                            ("correction", "Correction"),
                            ("discount", "Discount"),
                            ("promo", "Promotional"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Positive = credit, Negative = debit",
                        max_digits=14,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="External reference (ticket, invoice, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "adjusted_by",
                    models.CharField(
                        blank=True,
                        help_text="User who made the adjustment",
                        max_length=100,
                    ),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=True)),
                ("approved_by", models.CharField(blank=True, max_length=100)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_applied",
                    models.BooleanField(
                        default=False, help_text="Has this been applied to costs?"
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_adjustments",
                        to="claude_sessions.message",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_adjustments",
                        to="claude_sessions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "-created_at"],
                        name="billing_cos_session_3ace14_idx",
                    ),
                    models.Index(
                        fields=["adjustment_type", "-created_at"],
                        name="billing_cos_adjustm_5a2d32_idx",
                    ),
                    models.Index(
                        fields=["is_applied", "-created_at"],
                        name="billing_cos_is_appl_0bc550_idx",
                    ),
                    models.Index(
                        fields=["requires_approval", "is_approved"],
                        name="billing_cos_require_db6085_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageCost",
            fields=[
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cost",
                        serialize=False,
                        to="claude_sessions.message",
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cache_creation_tokens", models.IntegerField(default=0)),
                ("cache_read_tokens", models.IntegerField(default=0)),
                ("cache_ephemeral_5m_tokens", models.IntegerField(default=0)),
                ("cache_ephemeral_1h_tokens", models.IntegerField(default=0)),
                ("thinking_tokens", models.IntegerField(default=0)),
                (
                    "input_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "output_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "cache_write_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "cache_read_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "cache_ephemeral_5m_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "cache_ephemeral_1h_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "thinking_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("model", models.CharField(blank=True, db_index=True, max_length=100)),
                ("service_tier", models.CharField(blank=True, max_length=50)),
                ("message_timestamp", models.DateTimeField(db_index=True)),
                ("is_batch", models.BooleanField(default=False)),
                (
                    "adjustment_amount",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Manual adjustment applied",
                        max_digits=12,
                    ),
                ),
                (
                    "adjustment_reason",
                    models.TextField(blank=True, help_text="Reason for adjustment"),
                ),
                (
                    "calculation_version",
                    models.IntegerField(
                        default=1, help_text="Version of cost calculation algorithm"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("recalculated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_costs",
                        to="claude_sessions.session",
                    ),
                ),
                (
                    "pricing_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pricing used for calculation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_costs",
                        to="billing.pricingtier",
                    ),
                ),
            ],
            options={
                "ordering": ["-message_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session", "-message_timestamp"],
                        name="billing_mes_session_4babc3_idx",
                    ),
                    models.Index(
                        fields=["model", "-message_timestamp"],
                        name="billing_mes_model_2a017c_idx",
                    ),
                    models.Index(
                        fields=["-total_cost"], name="billing_mes_total_c_bccc44_idx"
                    ),
                    models.Index(
                        fields=["-calculated_at"], name="billing_mes_calcula_451ec7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RateLimitUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField(db_index=True)),
                ("period_end", models.DateTimeField()),
                (
                    "scope_value",
                    models.CharField(
                        blank=True,
                        help_text="Actual scope value for this usage record",
                        max_length=200,
                    ),
                ),
                (
                    "consumed_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("consumed_input_tokens", models.BigIntegerField(default=0)),
                ("consumed_output_tokens", models.BigIntegerField(default=0)),
                ("consumed_requests", models.IntegerField(default=0)),
                (
                    "consumed_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("alert_triggered", models.BooleanField(default=False)),
                ("alert_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("limit_exceeded", models.BooleanField(default=False)),
                ("limit_exceeded_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rate_limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="billing.ratelimit",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["rate_limit", "-period_start"],
                        name="billing_rat_rate_li_e5bf5c_idx",
                    ),
                    models.Index(
                        fields=["limit_exceeded", "-period_start"],
                        name="billing_rat_limit_e_a0031e_idx",
                    ),
                    models.Index(
                        fields=["alert_triggered", "-period_start"],
                        name="billing_rat_alert_t_8322b3_idx",
                    ),
                ],
                "unique_together": {("rate_limit", "period_start", "scope_value")},
            },
        ),
        migrations.CreateModel(
            name="SessionCostByModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(db_index=True, max_length=100)),
                ("input_tokens", models.BigIntegerField(default=0)),
                ("output_tokens", models.BigIntegerField(default=0)),
                ("cache_tokens", models.BigIntegerField(default=0)),
                ("thinking_tokens", models.BigIntegerField(default=0)),
                (
                    "input_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "output_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "cache_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "thinking_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_by_model",
                        to="claude_sessions.session",
                    ),
                ),
                (
                    "session_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="by_model",
                        to="billing.sessioncost",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_cost"],
                "indexes": [
                    models.Index(
                        fields=["session", "model"],
                        name="billing_ses_session_de2d2f_idx",
                    ),
                    models.Index(
                        fields=["model", "-total_cost"],
                        name="billing_ses_model_6d43d4_idx",
                    ),
                ],
                "unique_together": {("session_cost", "model")},
            },
        ),
        migrations.CreateModel(
            name="SessionCostByTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("input_tokens", models.BigIntegerField(default=0)),
                ("output_tokens", models.BigIntegerField(default=0)),
                (
                    "input_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "output_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("tool_use_count", models.IntegerField(default=0)),
                ("message_count", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_by_tool",
                        to="claude_sessions.session",
                    ),
                ),
                (
                    "session_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="by_tool",
                        to="billing.sessioncost",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_cost"],
                "indexes": [
                    models.Index(
                        fields=["session", "tool_name"],
                        name="billing_ses_session_c77eb6_idx",
                    ),
                    models.Index(
                        fields=["tool_name", "-total_cost"],
                        name="billing_ses_tool_na_92d7ed_idx",
                    ),
                ],
                "unique_together": {("session_cost", "tool_name")},
            },
        ),
    ]
