# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="SHA-256 hash of URL (first 16 chars)",
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(db_index=True, max_length=2000, unique=True)),
                ("canonical_url", models.URLField(blank=True, max_length=2000)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("github_repo", "GitHub Repository"),
                            ("github_issue", "GitHub Issue"),
                            ("github_user", "GitHub User"),
                            ("github_file", "GitHub File"),
                            ("documentation", "Documentation"),
                            ("blog_post", "Blog Post"),
                            ("reddit_subreddit", "Reddit Subreddit"),
                            ("reddit_post", "Reddit Post"),
                            ("youtube_channel", "YouTube Channel"),
                            ("youtube_video", "YouTube Video"),
                            ("changelog_entry", "Changelog Entry"),
                            ("api_reference", "API Reference"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("seed", "Seed"),
                            ("queued", "Queued"),
                            ("fetched", "Fetched"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("stale", "Stale"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.FloatField(
                        db_index=True,
                        default=0.5,
                        help_text="0.0 to 1.0, higher = more important",
                    ),
                ),
                ("priority_reasoning", models.TextField(blank=True)),
                ("priority_computed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "depth",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Distance from seed resources",
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of fetched content for change detection",
                        max_length=64,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resource this was discovered from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="knowledge.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="content",
                        serialize=False,
                        to="knowledge.resource",
                    ),
                ),
                (
                    "markdown",
                    models.TextField(
                        blank=True, help_text="Original or converted markdown"
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="Plain text for search/embedding"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="AI-generated summary"),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "extracted_links",
                    models.JSONField(
                        blank=True, default=list, help_text="URLs found in content"
                    ),
                ),
                (
                    "code_examples",
                    models.JSONField(
                        blank=True, default=list, help_text="Code blocks extracted"
                    ),
                ),
                (
                    "headings",
                    models.JSONField(
                        blank=True, default=list, help_text="Document structure"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Contents",
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("links_to", "Links To"),
                            ("mentioned_in", "Mentioned In"),
                            ("related_to", "Related To"),
                            ("depends_on", "Depends On"),
                            ("authored_by", "Authored By"),
                            ("belongs_to", "Belongs To"),
                            ("references", "References"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True, help_text="Context where relationship was found"
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0, help_text="Confidence score 0.0-1.0"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="knowledge.resource",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="knowledge.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding_type",
                    models.CharField(
                        choices=[
                            ("content", "Content Embedding"),
                            ("summary", "Summary Embedding"),
                            ("title", "Title Embedding"),
                            ("code", "Code Embedding"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            (
                                "text-embedding-3-small",
                                "OpenAI text-embedding-3-small (1536d)",
                            ),
                            (
                                "text-embedding-3-large",
                                "OpenAI text-embedding-3-large (3072d)",
                            ),
                            ("all-MiniLM-L6-v2", "all-MiniLM-L6-v2 (384d)"),
                            ("voyage-code-2", "Voyage Code 2 (1024d)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                (
                    "embedding_half",
                    pgvector.django.halfvec.HalfVectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="knowledge.resource",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["status", "-priority"], name="knowledge_r_status_c6b332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["source_type", "status"], name="knowledge_r_source__e7cfc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["depth", "status"], name="knowledge_r_depth_559f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["source", "edge_type"], name="knowledge_e_source__888ebf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["target", "edge_type"], name="knowledge_e_target__2fbc1f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="edge",
            unique_together={("source", "target", "edge_type")},
        ),
        migrations.AddIndex(
            model_name="embedding",
            index=models.Index(
                fields=["embedding_type", "model"],
                name="knowledge_e_embeddi_34dc7e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="embedding",
            unique_together={("resource", "embedding_type", "model")},
        ),
    ]
