# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        db_index=True,
                        help_text="Plugin marketplace/source",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("version", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=100)),
                ("repository_url", models.URLField(blank=True)),
                ("install_path", models.TextField(help_text="Local installation path")),
                ("cache_path", models.TextField(help_text="Cached plugin path")),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["marketplace", "name"],
                "indexes": [
                    models.Index(
                        fields=["enabled"], name="plugins_plu_enabled_19ca92_idx"
                    ),
                    models.Index(
                        fields=["-installed_at"], name="plugins_plu_install_949119_idx"
                    ),
                ],
                "unique_together": {("marketplace", "name", "version")},
            },
        ),
        migrations.CreateModel(
            name="PluginDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dependency_name", models.CharField(max_length=100)),
                ("dependency_version", models.CharField(blank=True, max_length=50)),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("plugin", "Plugin"),
                            ("system", "System"),
                            ("npm", "NPM"),
                            ("pip", "Pip"),
                        ],
                        default="plugin",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="plugins.plugin",
                    ),
                ),
            ],
            options={
                "unique_together": {("plugin", "dependency_name", "dependency_type")},
            },
        ),
    ]
