# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claude_sessions", "0001_initial"),
        ("plugins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubagentSession",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Subagent session ID",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parent_message_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "subagent_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., Explore, code-architect",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("prompt", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("result_summary", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("transcript_file", models.TextField(blank=True)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subagents",
                        to="claude_sessions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SubagentResult",
            fields=[
                (
                    "subagent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="result",
                        serialize=False,
                        to="agents.subagentsession",
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("partial", "Partial"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("result_metadata", models.JSONField(blank=True, null=True)),
                ("artifacts_generated", models.IntegerField(default=0)),
                ("files_modified", models.IntegerField(default=0)),
                ("lines_changed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubagentToolUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("input_params", models.JSONField(blank=True, null=True)),
                ("output_result", models.TextField(blank=True)),
                ("success", models.BooleanField(db_index=True, default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "subagent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_uses",
                        to="agents.subagentsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("file_path", models.TextField()),
                ("tools", models.TextField(blank=True, help_text="Available tools")),
                ("model", models.CharField(blank=True, db_index=True, max_length=50)),
                ("prompt", models.TextField(help_text="Agent system prompt")),
                ("frontmatter", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plugin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="plugins.plugin",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("plugin", "name")},
            },
        ),
        migrations.CreateModel(
            name="SubagentHierarchy",
            fields=[
                (
                    "subagent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hierarchy",
                        serialize=False,
                        to="agents.subagentsession",
                    ),
                ),
                ("depth", models.IntegerField(db_index=True, default=0)),
                (
                    "path",
                    models.TextField(help_text="Materialized path of session IDs"),
                ),
                (
                    "parent_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_children",
                        to="claude_sessions.session",
                    ),
                ),
                (
                    "root_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subagent_hierarchy_roots",
                        to="claude_sessions.session",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subagentsession",
            index=models.Index(
                fields=["subagent_type", "-started_at"],
                name="agents_suba_subagen_dc046a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subagentsession",
            index=models.Index(
                fields=["status", "-started_at"], name="agents_suba_status_2274ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subagenttooluse",
            index=models.Index(
                fields=["tool_name", "-timestamp"],
                name="agents_suba_tool_na_de16fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subagenthierarchy",
            index=models.Index(
                fields=["root_session", "depth"], name="agents_suba_root_se_79c08f_idx"
            ),
        ),
    ]
