# Generated by Django 6.0.1 on 2026-01-28 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claude_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_name", models.CharField(db_index=True, max_length=100)),
                ("command", models.TextField(help_text="Command to start the server")),
                ("args_json", models.JSONField(blank=True, default=list)),
                ("env_json", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("auto_start", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_servers",
                        to="claude_settings.settingsprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP Server",
                "verbose_name_plural": "MCP Servers",
                "unique_together": {("profile", "server_name")},
            },
        ),
    ]
